---
# meta file for install_packages

galaxy_info:
  author: Omid Fallah Karimi
  description: Install packages on Linux systems (supports multiple distributions)
  license: GPL-2.0-or-later
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: opensuse
      versions:
        - all

  galaxy_tags:
    - packages
    - system
    - linux
    - installation

dependencies: []
