---
# Debian/Ubuntu specific variables

docker_old_packages:
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc

docker_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_apt_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_apt_repository: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
