---
# RedHat/CentOS specific variables

docker_old_packages:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine

docker_prerequisites:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2

docker_yum_repository: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
docker_yum_gpg_key: "https://download.docker.com/linux/centos/gpg"
