---
# meta file for add_repository

galaxy_info:
  author: Omid Fallah Karimi
  description: Add package repositories on Linux systems (supports multiple distributions)
  license: GPL-2.0-or-later
  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Archlinux
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: opensuse
      versions:
        - all

  galaxy_tags:
    - repository
    - packages
    - system
    - linux
    - apt
    - yum
    - dnf

dependencies: []
