---
# Example: Add EPEL repository on CentOS/RHEL

- name: Add EPEL repository
  hosts: all
  become: true
  roles:
    - role: omid_fallah_karimi.devops_toolkit.add_repository
      vars:
        # Optional: Skip GPG key verification (default: false)
        # skip_gpg_check: false
        
        # Optional: Remove all existing repos first (default: false)
        # purge_existing_repos: false
        
        yum_repositories:
          - name: "epel"
            description: "Extra Packages for Enterprise Linux $releasever - $basearch"
            baseurl: "https://dl.fedoraproject.org/pub/epel/$releasever/$basearch/"
            gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever"
            gpgcheck: true
            enabled: true
